<a href="https://colab.research.google.com/github/Ishicka/deep-learning-challenge/blob/main/AlphabetSoupCharity_Optimization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN'
application_df = application_df.drop(columns=['EIN'])
application_df.head()

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
name_count = application_df['NAME'].value_counts()
name_count[name_count > 50]

NAME
PARENT BOOSTER USA INC                                                1260
TOPS CLUB INC                                                          765
UNITED STATES BOWLING CONGRESS INC                                     700
WASHINGTON STATE UNIVERSITY                                            492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                        408
PTA TEXAS CONGRESS                                                     368
SOROPTIMIST INTERNATIONAL OF THE AMERICAS INC                          331
ALPHA PHI SIGMA                                                        313
TOASTMASTERS INTERNATIONAL                                             293
MOST WORSHIPFUL STRINGER FREE AND ACCEPTED MASONS                      287
LITTLE LEAGUE BASEBALL INC                                             277
INTERNATIONAL ASSOCIATION OF LIONS CLUBS                               266
MOMS CLUB                                                              210
INTERNATIONAL ASSOCIATION OF SHEET METAL AIR RAIL & TRANSPORTATION     206
AMERICAN ASSOCIATION OF UNIVERSITY WOMEN                               197
FARMERS EDUCATIONAL AND COOPERATIVE UNION OF AMERICA                   166
KNIGHTS OF COLUMBUS                                                    158
HABITAT FOR HUMANITY INTERNATIONAL INC                                 154
TENNESSEE ORDER OF THE EASTERN STAR                                    151
VETERANS OF FOREIGN WARS OF THE UNITED STATES AUXILIARY                144
PTA UTAH CONGRESS                                                      140
THE UNITED STATES PONY CLUBS INC                                       136
CIVITAN INTERNATIONAL                                                  131
SIGMA BETA DELTA INC                                                   127
HONOR SOCIETY OF PHI KAPPA PHI                                         107
MONTANA 4-H FOUNDATION INC                                             107
WASHINGTON STATE GRANGE                                                106
UNIVERSITY OF WYOMING                                                  105
DEMOLAY INTERNATIONAL                                                  104
SERTOMA INC                                                            103
AIR FORCE ASSOCIATION                                                   99
WORKERS UNITED                                                          97
GAMMA THETA UPSILON                                                     92
INTERNATIONAL ASSOCIATION OF FIRE FIGHTERS                              91
SOCIETY OF SAINT VINCENT DE PAUL COUNCIL OF LOS ANGELES                 87
ROTARY INTERNATIONAL                                                    84
CALIFORNIA GARDEN CLUBS INC                                             76
SWEET ADELINES INTERNATIONAL                                            73
DISABLED AMERICAN VETERANS                                              73
KLEIN SUPPORT GROUPS INC                                                69
CLEARCREEK I S D SUPPORT GROUPS                                         60
VFW AUXILIARY DEPARTMENT OF OKLAHOMA INC                                58
DEPARTMENT OF KANSAS LADIES AUXILIARY TO THE VFW OF THE US INC          57
CISD EDUCATIONAL SUPPORT GROUPS INC                                     57
SONS OF CONFEDERATE VETERANS INC                                        56
SLOW FOOD USA INC                                                       55
NATIONAL YOUNG MENS SERVICE LEAGUE                                      54
AMATEUR ATHLETIC UNION OF THE UNITED STATES                             52
LAMBDA THETA ALPHA                                                      52
Name: count, dtype: int64

In [4]:
name_types_to_replace = list(name_count[name_count < 50].index)

# Replace in dataframe
for name in name_types_to_replace:
    application_df['NAME'] = application_df['NAME'].replace(name,"Other")

# Check to make sure binning was successful
application_df['NAME'].value_counts()

NAME
Other                                                                 24545
PARENT BOOSTER USA INC                                                 1260
TOPS CLUB INC                                                           765
UNITED STATES BOWLING CONGRESS INC                                      700
WASHINGTON STATE UNIVERSITY                                             492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                         408
PTA TEXAS CONGRESS                                                      368
SOROPTIMIST INTERNATIONAL OF THE AMERICAS INC                           331
ALPHA PHI SIGMA                                                         313
TOASTMASTERS INTERNATIONAL                                              293
MOST WORSHIPFUL STRINGER FREE AND ACCEPTED MASONS                       287
LITTLE LEAGUE BASEBALL INC                                              277
INTERNATIONAL ASSOCIATION OF LIONS CLUBS                                266
MOMS CLUB                                                               210
INTERNATIONAL ASSOCIATION OF SHEET METAL AIR RAIL & TRANSPORTATION      206
AMERICAN ASSOCIATION OF UNIVERSITY WOMEN                                197
FARMERS EDUCATIONAL AND COOPERATIVE UNION OF AMERICA                    166
KNIGHTS OF COLUMBUS                                                     158
HABITAT FOR HUMANITY INTERNATIONAL INC                                  154
TENNESSEE ORDER OF THE EASTERN STAR                                     151
VETERANS OF FOREIGN WARS OF THE UNITED STATES AUXILIARY                 144
PTA UTAH CONGRESS                                                       140
THE UNITED STATES PONY CLUBS INC                                        136
CIVITAN INTERNATIONAL                                                   131
SIGMA BETA DELTA INC                                                    127
MONTANA 4-H FOUNDATION INC                                              107
HONOR SOCIETY OF PHI KAPPA PHI                                          107
WASHINGTON STATE GRANGE                                                 106
UNIVERSITY OF WYOMING                                                   105
DEMOLAY INTERNATIONAL                                                   104
SERTOMA INC                                                             103
AIR FORCE ASSOCIATION                                                    99
WORKERS UNITED                                                           97
GAMMA THETA UPSILON                                                      92
INTERNATIONAL ASSOCIATION OF FIRE FIGHTERS                               91
SOCIETY OF SAINT VINCENT DE PAUL COUNCIL OF LOS ANGELES                  87
ROTARY INTERNATIONAL                                                     84
CALIFORNIA GARDEN CLUBS INC                                              76
SWEET ADELINES INTERNATIONAL                                             73
DISABLED AMERICAN VETERANS                                               73
KLEIN SUPPORT GROUPS INC                                                 69
CLEARCREEK I S D SUPPORT GROUPS                                          60
VFW AUXILIARY DEPARTMENT OF OKLAHOMA INC                                 58
CISD EDUCATIONAL SUPPORT GROUPS INC                                      57
DEPARTMENT OF KANSAS LADIES AUXILIARY TO THE VFW OF THE US INC           57
SONS OF CONFEDERATE VETERANS INC                                         56
SLOW FOOD USA INC                                                        55
NATIONAL YOUNG MENS SERVICE LEAGUE                                       54
AMATEUR ATHLETIC UNION OF THE UNITED STATES                              52
LAMBDA THETA ALPHA                                                       52
UNITED FEDERATION OF DOLL CLUBS INC                                      50
UNIVERSITY OF FLORIDA                                                    50
Name: count, dtype: int64

In [5]:
# Determine the number of unique values in each column.
application_df.nunique()

NAME                        52
APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [6]:
# Look at APPLICATION_TYPE value counts for binning
application_type_count = application_df['APPLICATION_TYPE'].value_counts()
application_type_count

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [7]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(application_type_count[application_type_count < 20].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
T13         66
Other       27
T12         27
Name: count, dtype: int64

In [8]:
# Look at CLASSIFICATION value counts for binning
classification_count = application_df['CLASSIFICATION'].value_counts()
classification_count[classification_count > 1]

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [9]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classification_count[classification_count < 100].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: count, dtype: int64

In [10]:
# Convert categorical data to numeric with `pd.get_dummies`
application_dummies = pd.get_dummies(application_df)
application_dummies.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_AIR FORCE ASSOCIATION,NAME_ALPHA PHI SIGMA,NAME_AMATEUR ATHLETIC UNION OF THE UNITED STATES,NAME_AMATEUR ATHLETIC UNION OF THE UNITED STATES INC,NAME_AMERICAN ASSOCIATION OF UNIVERSITY WOMEN,NAME_CALIFORNIA GARDEN CLUBS INC,NAME_CISD EDUCATIONAL SUPPORT GROUPS INC,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,True,False

In [11]:
# Split our preprocessed data into our features and target arrays
y = application_dummies['IS_SUCCESSFUL'].values

X = application_dummies.drop(columns='IS_SUCCESSFUL').values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    random_state=1)

In [12]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [13]:
num_input_features = len(X_train_scaled[1])
print(f"Number of Input Features : {num_input_features}")

Number of Input Features : 104

In [14]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE
hidden_nodes_layer1 =  150
hidden_nodes_layer2 = 100
hidden_nodes_layer3 = 50
hidden_nodes_layer4 = 25

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=num_input_features, activation="relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="relu"))

# Fourth hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer4, activation="tanh"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 150)               15750

 dense_1 (Dense)             (None, 100)               15100

 dense_2 (Dense)             (None, 50)                5050

 dense_3 (Dense)             (None, 25)                1275

 dense_4 (Dense)             (None, 1)                 26

=================================================================
Total params: 37201 (145.32 KB)
Trainable params: 37201 (145.32 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [15]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [16]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 4s 3ms/step - loss: 0.4950 - accuracy: 0.7545
Epoch 2/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4787 - accuracy: 0.7633
Epoch 3/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4749 - accuracy: 0.7664
Epoch 4/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4723 - accuracy: 0.7683
Epoch 5/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4722 - accuracy: 0.7683
Epoch 6/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4703 - accuracy: 0.7695
Epoch 7/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4696 - accuracy: 0.7696
Epoch 8/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4684 - accuracy: 0.7703
Epoch 9/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4681 - accuracy: 0.7688
Epoch 10/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4671 - accuracy: 0.7703
Epoch 11/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4663 - accuracy: 0.7715
Epoch 12/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4665 - accuracy: 0.7711
Epoch 13/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4657 - accuracy: 0.7718
Epoch 14/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4646 - accuracy: 0.7721
Epoch 15/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4650 - accuracy: 0.7732
Epoch 16/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4642 - accuracy: 0.7727
Epoch 17/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4639 - accuracy: 0.7741
Epoch 18/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4630 - accuracy: 0.7731
Epoch 19/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4628 - accuracy: 0.7735
Epoch 20/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4626 - accuracy: 0.7739
Epoch 21/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4617 - accuracy: 0.7742
Epoch 22/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4608 - accuracy: 0.7751
Epoch 23/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4605 - accuracy: 0.7742
Epoch 24/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4607 - accuracy: 0.7747
Epoch 25/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4599 - accuracy: 0.7744
Epoch 26/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4601 - accuracy: 0.7737
Epoch 27/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4596 - accuracy: 0.7741
Epoch 28/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4590 - accuracy: 0.7756
Epoch 29/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4593 - accuracy: 0.7750
Epoch 30/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4583 - accuracy: 0.7752
Epoch 31/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4579 - accuracy: 0.7755
Epoch 32/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4588 - accuracy: 0.7745
Epoch 33/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4574 - accuracy: 0.7757
Epoch 34/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4577 - accuracy: 0.7749
Epoch 35/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4584 - accuracy: 0.7756
Epoch 36/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4583 - accuracy: 0.7748
Epoch 37/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4573 - accuracy: 0.7743
Epoch 38/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4577 - accuracy: 0.7747
Epoch 39/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4573 - accuracy: 0.7758
Epoch 40/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4570 - accuracy: 0.7752
Epoch 41/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4566 - accuracy: 0.7760
Epoch 42/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4561 - accuracy: 0.7759
Epoch 43/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4562 - accuracy: 0.7768
Epoch 44/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4560 - accuracy: 0.7759
Epoch 45/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4555 - accuracy: 0.7764
Epoch 46/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4567 - accuracy: 0.7747
Epoch 47/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4569 - accuracy: 0.7767
Epoch 48/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4561 - accuracy: 0.7757
Epoch 49/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4574 - accuracy: 0.7748
Epoch 50/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4568 - accuracy: 0.7758
Epoch 51/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4567 - accuracy: 0.7764
Epoch 52/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4574 - accuracy: 0.7754
Epoch 53/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4565 - accuracy: 0.7755
Epoch 54/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4563 - accuracy: 0.7767
Epoch 55/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4567 - accuracy: 0.7752
Epoch 56/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4563 - accuracy: 0.7756
Epoch 57/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4549 - accuracy: 0.7763
Epoch 58/100
804/804 [==============================] - 4s 4ms/step - loss: 0.4563 - accuracy: 0.7753
Epoch 59/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4554 - accuracy: 0.7754
Epoch 60/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4550 - accuracy: 0.7766
Epoch 61/100
804/804 [==============================] - 4s 4ms/step - loss: 0.4542 - accuracy: 0.7772
Epoch 62/100
804/804 [==============================] - 7s 8ms/step - loss: 0.4561 - accuracy: 0.7757
Epoch 63/100
804/804 [==============================] - 5s 7ms/step - loss: 0.4555 - accuracy: 0.7754
Epoch 64/100
804/804 [==============================] - 6s 8ms/step - loss: 0.4555 - accuracy: 0.7766
Epoch 65/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4557 - accuracy: 0.7766
Epoch 66/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4556 - accuracy: 0.7766
Epoch 67/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4555 - accuracy: 0.7757
Epoch 68/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4558 - accuracy: 0.7765
Epoch 69/100
804/804 [==============================] - 5s 6ms/step - loss: 0.4542 - accuracy: 0.7772
Epoch 70/100
804/804 [==============================] - 5s 6ms/step - loss: 0.4543 - accuracy: 0.7767
Epoch 71/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4543 - accuracy: 0.7774
Epoch 72/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4553 - accuracy: 0.7766
Epoch 73/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4554 - accuracy: 0.7756
Epoch 74/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4535 - accuracy: 0.7770
Epoch 75/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4544 - accuracy: 0.7773
Epoch 76/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4547 - accuracy: 0.7759
Epoch 77/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4550 - accuracy: 0.7762
Epoch 78/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4550 - accuracy: 0.7766
Epoch 79/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4543 - accuracy: 0.7769
Epoch 80/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4544 - accuracy: 0.7766
Epoch 81/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4557 - accuracy: 0.7755
Epoch 82/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4543 - accuracy: 0.7761
Epoch 83/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4546 - accuracy: 0.7772
Epoch 84/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4538 - accuracy: 0.7773
Epoch 85/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4546 - accuracy: 0.7771
Epoch 86/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4557 - accuracy: 0.7766
Epoch 87/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4546 - accuracy: 0.7771
Epoch 88/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4538 - accuracy: 0.7773
Epoch 89/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4544 - accuracy: 0.7766
Epoch 90/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4549 - accuracy: 0.7757
Epoch 91/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4544 - accuracy: 0.7768
Epoch 92/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4565 - accuracy: 0.7759
Epoch 93/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4558 - accuracy: 0.7734
Epoch 94/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4555 - accuracy: 0.7764
Epoch 95/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4553 - accuracy: 0.7770
Epoch 96/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4538 - accuracy: 0.7774
Epoch 97/100
804/804 [==============================] - 5s 6ms/step - loss: 0.4546 - accuracy: 0.7759
Epoch 98/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4547 - accuracy: 0.7771
Epoch 99/100
804/804 [==============================] - 4s 6ms/step - loss: 0.4539 - accuracy: 0.7775
Epoch 100/100
804/804 [==============================] - 6s 7ms/step - loss: 0.4536 - accuracy: 0.7778

In [17]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.4979 - accuracy: 0.7628 - 585ms/epoch - 2ms/step
Loss: 0.4978616535663605, Accuracy: 0.7627988457679749

In [19]:
# Export our model to HDF5 file
nn.save('AlphabetSoupCharity_Optimization.h5')